Added more robust functionality, made simpler

diff --git a/viuscript b/viuscript
--- a/viuscript
+++ b/viuscript
@@ -9,31 +9,41 @@
 
 ##  Constants
 SERVER="csci.viu.ca"
-IPSERVER="142.25.101.2"
 
-##  takes input from -i and -l command
+##  takes input -l command
 function login {
-  local arg1=$1
-  local arg2=$2
+  local id=$1
   clear
-  if [[ $arg1 && $arg2 ]]; then
-    printf "Logging into VIU server via ip..\n\n"
-    ssh -l "$arg1" "$IPSERVER"
-  else
-    printf  "Logging into VIU server..\n\n"
-    ssh -l "$arg1" "$SERVER"
-    local sshRet=$?
-    if [[ ! "$sshRet" ]]; then
-      printf "ssh failure\n"
-    fi
- fi
+  printf  "Logging into VIU server..\n\n"
+  ssh -l "$id" "$SERVER"
+  local sshRet=$?
+  if [[ ! "$sshRet" ]]; then
+    printf "ssh failure\n"
+  fi
 }
 
-##  using scp file tranfer protocol
-function fileTransfer {
+## transfer files from local machine to server
+function transferToServer {
+  filename="$1" 
+  id="$2" 
+
   clear
   printf "Transferring your files..\n\n"
-  scp "$1" "$2@$SERVER:$3"
+  scp "$filename" "$id@$SERVER:$filename"
+  scpRet=$?
+  if [[ ! "$scpRet" ]]; then
+    printf "scp failure\n"
+  fi
+}
+
+# Transfer files to local machine from server
+function transferToLocal {
+  id="$1"
+  filename="$2"
+
+  clear
+  printf "Transferring your files..\n\n"
+  scp "$id" "$filename@$SERVER:$filename"
   scpRet=$?
   if [[ ! "$scpRet" ]]; then
     printf "scp failure\n"
@@ -47,19 +57,22 @@ function displayHelp {
   printf  "\tviuScript is meant to mitigate the login and file transfer process\n"
   printf  "\tAll this information can be found on Dave Wessels Technotes page.\n"
   printf  "\thttp://csci.viu.ca/~wesselsd/technotes.html\n"
-  printf  "\t-i <yourUserName>      use ip address to login\n"
+  printf  "\t-t sends files from your machine to the server\n"
+  printf  "\t-m sends files from the server to your machine\n"
   printf  "\t-l <yourUserName>      Login using standard method\n"
+  printf  "\t-t <file> <yourloginId>\n"
+  printf  "\t-m <yourloginId> <file>\n"
   printf  "\t-h                     Display this menu\n"
-  printf  "\t-t <file> <yourloginId> /path/to/where/you/want\n"
-  printf  "\t[e.g] viuScript -t lab2.cpp johnQpublic csci161/lab2.cpp\n\n"
+  printf  "\t[e.g] viuScript -t lab2.cpp johnQpublic\n\n"
+  printf  "\t[e.g] viuScript -m johnQpublic lab2.cpp\n\n"
 }
 
 # usage function
 function noArrgs {
   echo "script usage: $(basename $0)
   [-l <yourloginId>]
-  [-i <yourloginId>]
-  [-t <file> <yourloginId> <file>]
+  [-t <file> <yourloginId> ]
+  [-m <yourloginId> <file> ]
   [-h Displays a detailed help menu]" >&2
   exit 1
 }
@@ -71,21 +84,21 @@ then
 fi
 
 # start the main loop
-while getopts 'l:i:t:h' OPTION; do
+while getopts 'l:t:m:h' OPTION; do
   case "$OPTION" in
     l)
-      login "$OPTARG"
+      id=$OPTARG
+      login "$id"
       ;;
     t)
-      tvalue2="$2"
-      tvalue3="$3"
-      tvalue4="$4"
-      fileTransfer "$tvalue2" "$tvalue3" "$tvalue4"
+      filename="$2"
+      id="$3"
+      transferToServer "$filename" "$id"
       ;;
-    i)
-      ivalue1="$1" # will hold -i but we use for the if statement in login
-      ivalue2="$2"
-      login "$ivalue1" "$ivalue2"
+    m)
+      id="$2"
+      filename="$3"
+      transferToLocal "$id" "$filename"
       ;;
     h)
       displayHelp
